version: '3.4'

volumes:
  peer0.org1.odins.com:


services:
  peer0.org1.odins.com:
    image: hyperledger/fabric-peer:2.4
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
     # - CORE_CHAINCODE_EXECUTETIMEOUT=60S
     # - CORE_PEER_KEEPALIVE_CLIENT_TIMEOUT=60S
     # - CORE_PEER_KEEPALIVE_DELIVERYCLIENT_TIMEOUT=60S
      - CORE_CHAINCODE_EXECUTETIMEOUT=30s
      - CORE_PEER_KEEPALIVE_DELIVERYCLIENT_TIMEOUT=30s
      - CORE_PEER_KEEPALIVE_CLIENT_TIMEOUT=30s
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=debian_default
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - FABRIC_LOGGING_SPEC=info
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
      - CORE_PEER_ID=peer0.org1.odins.com
      - CORE_PEER_ADDRESS=peer0.org1.odins.com:7051
      - CORE_PEER_GOSSIP_USELEADERELECTION=false
      - CORE_PEER_GOSSIP_ORGLEADER=true
      #- CORE_PEER_GOSSIP_BOOTSTRAP=10.9.25.30:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.odins.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_VM_DOCKER_ATTACHSTDOUT=true
      - CORE_CHAINCODE_STARTUPTIMEOUT=1200s
      - CORE_CHAINCODE_EXECUTETIMEOUT=800s
      - ORDERER_CA=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/odins.com/orderers/orderer.odins.com/msp/tlscacerts/tlsca.odins.com-cert.pem
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.odins.com:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    restart: always
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start

    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/org1.odins.com/peers/peer0.org1.odins.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/org1.odins.com/peers/peer0.org1.odins.com/tls:/etc/hyperledger/fabric/tls
        - peer0.org1.odins.com:/var/hyperledger/production
    ports:
      - "7051:7051"
      - "7052:7052"
      - "7053:7053"
  couchdb.odins.com:
    container_name: couchdb
    image: couchdb:2.1.1
    labels:
      service: hyperledger-fabric
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for odins map it to utilize Fauxton User Interface in dev environments.
    ports:
      - "5984:5984"
